#!/bin/bash

# Add this to sudoers file:
# username ALL=(ALL) NOPASSWD: /path/to/script

max_brightness=$(cat /sys/class/backlight/intel_backlight/max_brightness)

function increase() {
    brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
    if [[ $brightness -lt $max_brightness ]]; then
        let brightness=$brightness+100
        echo $brightness > /sys/class/backlight/intel_backlight/brightness
    fi
}

function decrease() {
    brightness=$(cat /sys/class/backlight/intel_backlight/brightness)
    if [[ $brightness -gt 0 ]]; then
        let brightness=$brightness-100
        echo $brightness > /sys/class/backlight/intel_backlight/brightness
    fi
}

if [[ $# -gt 0 ]]; then
    if [[ $1 == "increase" ]]; then
        increase
    elif [[ $1 == "decrease" ]]; then
        decrease
    fi
else
    echo "Usage: $0 [increase | decrease]"
fi
