#!/bin/bash

function build_vim() {
    cd "$HOME/vim/src"
    make distclean &&
    ./configure --with-features=huge \
        --enable-rubyinterp \
        --enable-largefile \
        --enable-netbeans \
        --enable-pythoninterp \
        --with-python-config-dir=/usr/lib/python2.7/config \
        --enable-perlinterp \
        --enable-gui=gtk2 \
        --enable-fail-if-missing \
        --enable-cscope
    make
    sudo make install
}

function update_vim() {
    # Check if vim exists as a command
    if [[ $(command -v vim) ]]; then
        cd "$HOME/vim/src"
        git stash
        git fetch
        LOCAL=$(git rev-parse @)
        REMOTE=$(git rev-parse "@{u}")

        # If local matches remote, and this isn't the first time cloning, then vim is up to date
        if [[ "$LOCAL" == "$REMOTE" ]]; then
            echo "Vim is up to date"
            return
        else
            # Local repo needs to be updated and vim needs to be rebuilt
            git merge origin/master
            build_vim
        fi
        version=$(vim --version | grep Vi\ IMproved)
        patches=$(vim --version | grep patches)
        echo "Vim is now updated"
        echo "$version"
        echo "$patches"

    else
        if [[ ! -d "$HOME/vim" ]]; then
            sudo apt-get -y remove --purge vim vim-runtime vim-gnome vim-tiny vim-common vim-gui-common
            sudo apt-get -y build-dep vim-gnome
            sudo apt-get -y install python-dev ruby-dev libperl-dev mercurial libncurses5-dev libgnome2-dev libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev libcairo2-dev libx11-dev libxpm-dev libxt-dev
            git clone https://github.com/vim/vim "$HOME/vim"
        fi
        cd "$HOME/vim/src"
        build_vim
    fi
}

set -e # Abort if any command exits with non-zero exit code
sudo -v

# Build override
if [[ "$1" == "--build" ]]; then
    build_vim
    exit 0
fi

update_vim
